export const wardSpecializationData = [
  "General Medicine",
  "Pediatrics",
  "Cardiology",
  "Orthopedics",
  "Oncology",
  "Gastroenterology",
  "Neurology",
  "Dermatology",
  "Pulmonology",
  "Nephrology",
  "Endocrinology",
  "Hematology",
  "Rheumatology",
  "Urology",
  "Gynecology",
  "Ophthalmology",
  "Otolaryngology",
  "Dentistry",
  "Psychiatry",
  "Radiology",
  "Surgery",
];
